// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table agentic_events (timestamp:datetime, trace_id:guid, session_id:string, user_id:string, message:dynamic, agent_name:string, user_message:string, filter_category:string, content_filter_info:dynamic) 
.create-or-alter table agentic_events ingestion json mapping 'agentic_events_mapping'
```
[{"Properties":{"Path":"$['timestamp']"},"column":"timestamp","datatype":""},{"Properties":{"Path":"$['trace_id']"},"column":"trace_id","datatype":""},{"Properties":{"Path":"$['session_id']"},"column":"session_id","datatype":""},{"Properties":{"Path":"$['user_id']"},"column":"user_id","datatype":""},{"Properties":{"Path":"$['message']"},"column":"message","datatype":""},{"Properties":{"Path":"$['agent_name']"},"column":"agent_name","datatype":""},{"Properties":{"Path":"$['user_message']"},"column":"user_message","datatype":""},{"Properties":{"Path":"$['filter_category']"},"column":"filter_category","datatype":""},{"Properties":{"Path":"$['content_filter_info']"},"column":"content_filter_info","datatype":""}]
```
